# Site settings
title: Renaud Martinet
email: karouf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://renaudmarti.net" # the base hostname & protocol for your site
twitter_username: karouf
github_username:  karouf

# Build settings
future: false
markdown: kramdown

kramdown:
  input: GFM
