# Site settings
title: Renaud Martinet
email: karouf@gmail.com
description: "Writings by Renaud Martinet."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://renaudmarti.net" # the base hostname & protocol for your site
twitter_username: karouf
github_username:  karouf

# Build settings
future: false
permalink: /posts/:title/
markdown: kramdown

kramdown:
  input: GFM

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
